---
- name: Установка и восстановление PostgreSQL 14
  hosts: db_servers
  become: yes
  vars:
    pg_version: 14
    db_name: mediawiki
    db_user: wikiuser
    db_password: "StrongPass!"
    db_backup_file: "/tmp/mediawiki_backup.sql"
    listen_address: "*"
    allow_network: "192.168.1.0/24"

  tasks:
    - name: Добавить репозиторий PostgreSQL
      apt_repository:
        repo: "deb http://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main"
        state: present
        filename: "pgdg"

    - name: Добавить ключ репозитория
      apt_key:
        url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
        state: present

    - name: Установить PostgreSQL {{ pg_version }}
      apt:
        name: "postgresql-{{ pg_version }}"
        state: present
        update_cache: yes

    - name: Убедиться, что PostgreSQL запущен
      service:
        name: postgresql
        state: started
        enabled: yes

    - name: Разрешить подключения по сети
      lineinfile:
        path: "/etc/postgresql/{{ pg_version }}/main/postgresql.conf"
        regexp: "^#?listen_addresses ="
        line: "listen_addresses = '{{ listen_address }}'"
        state: present

    - name: Разрешить подключения от хостов {{ allow_network }}
      lineinfile:
        path: "/etc/postgresql/{{ pg_version }}/main/pg_hba.conf"
        insertafter: EOF
        line: "host all all {{ allow_network }} md5"

    - name: Перезапустить PostgreSQL
      service:
        name: postgresql
        state: restarted

    - name: Создать пользователя базы данных
      become_user: postgres
      postgresql_user:
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        role_attr_flags: "LOGIN"

    - name: Создать базу данных
      become_user: postgres
      postgresql_db:
        name: "{{ db_name }}"
        owner: "{{ db_user }}"
        encoding: "UTF8"
        lc_collate: "en_US.UTF-8"
        lc_ctype: "en_US.UTF-8"
        template: "template0"
        state: present

    - name: Скопировать файл резервной копии
      copy:
        src: "./mediawiki_backup.sql"
        dest: "{{ db_backup_file }}"
        mode: "0644"

    - name: Восстановить базу из бэкапа
      become_user: postgres
      command: >
        psql -d {{ db_name }} -f {{ db_backup_file }}
      register: restore_result
      ignore_errors: yes

    - name: Проверить результат восстановления
      debug:
        msg: "Результат восстановления: {{ restore_result.stdout | default('нет вывода') }}"
