---
- name: Restore Zabbix Server (MySQL) from backup
  hosts: zabbix
  become: yes

  vars:
    db_name: zabbix
    db_user: zabbix
    db_password: ZabbixPass123!
    backup_dir: /backup
    backup_sql: "{{ backup_dir }}/zabbix_backup.sql"
    
    backup_conf: "{{ backup_dir }}/zabbix_server.conf"
    backup_web_conf: "{{ backup_dir }}/zabbix.conf.php"

  tasks:
    - name: Ensure Zabbix repository is installed
      ansible.builtin.shell: |
        wget -q https://repo.zabbix.com/zabbix/7.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_7.0-2+ubuntu$(lsb_release -rs)_all.deb -O /tmp/zabbix-release.deb
        dpkg -i /tmp/zabbix-release.deb
        apt update -y


    - name: Install Zabbix and MySQL packages
      ansible.builtin.apt:
        name:
          - zabbix-server-mysql
          - zabbix-frontend-php
          - zabbix-apache-conf
          - zabbix-sql-scripts
          - zabbix-agent
          - mysql-server
        state: present
        update_cache: yes

    - name: Ensure MySQL is running
      ansible.builtin.systemd:
        name: mysql
        state: started
        enabled: yes

    - name: Create Zabbix database and user
      ansible.builtin.shell: |
        mysql -u root -e "CREATE DATABASE IF NOT EXISTS {{ db_name }} CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;"
        mysql -u root -e "CREATE USER IF NOT EXISTS '{{ db_user }}'@'localhost' IDENTIFIED BY '{{ db_password }}';"
        mysql -u root -e "GRANT ALL PRIVILEGES ON {{ db_name }}.* TO '{{ db_user }}'@'localhost'; FLUSH PRIVILEGES;"

    - name: Restore Zabbix database from SQL backup
      ansible.builtin.shell: |
        mysql -u root {{ db_name }} < {{ backup_sql }}
      args:
        warn: false

    - name: Restore Zabbix server config
      ansible.builtin.copy:
        src: ./files/zabbix_server.conf
        dest: /etc/zabbix/zabbix_server.conf
        owner: zabbix
        group: zabbix
        mode: '0644'

    - name: Restore Zabbix frontend config (zabbix.conf.php)
      ansible.builtin.copy:
        src: ./files/zabbix.conf.php
        dest: /etc/zabbix/web/zabbix.conf.php
        owner: www-data
        group: www-data
        mode: '0644'
      when: backup_web_conf is exists
      
    - name: Restart services
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: restarted
        enabled: yes
      loop:
        - mysql
        - zabbix-server
        - zabbix-agent
        - apache2
